"""
🛡️ ZTC-Wrapper - Tests del Wrapper

Tests para el AI Agent Wrapper.
"""

import pytest
from src.wrapper import AIAgentWrapper, WrapperConfig, WrapperResult


class TestAIAgentWrapper:
    """Tests para el AIAgentWrapper."""

    def test_wrapper_initialization(self):
        """Debe inicializar correctamente."""
        wrapper = AIAgentWrapper()

        assert wrapper.sanitizer is not None
        assert wrapper.extractor is not None
        assert wrapper.detector is not None

    def test_sanitize_input(self):
        """Debe sanitizar el input."""
        wrapper = AIAgentWrapper()

        prompt = """
// Generated by Claude Code
session_id = "abc-123"
"""

        config = WrapperConfig(
            agent_command="demo",
            sanitize_input=True,
            sanitize_output=False,
            block_critical=False,
        )

        result = wrapper.run(prompt, config)

        assert result.sanitized_input is True
        assert "Generated by" not in result.stdout
        assert "abc-123" not in result.stdout

    def test_block_critical_issues(self):
        """Debe bloquear output con problemas críticos."""
        wrapper = AIAgentWrapper()

        # Simular output vulnerable
        prompt = "Genera código"

        config = WrapperConfig(
            agent_command="demo",
            sanitize_input=False,
            sanitize_output=True,
            block_critical=True,
        )

        # Simular un output con eval()
        # El wrapper no ejecuta el agente, así que no podemos testear directamente
        # En su lugar, testeamos el detector
        from src.detector import LegacyShield

        detector = LegacyShield()
        issues = detector.scan_code("result = eval(user_input)")

        assert len(issues) > 0
        assert detector.block_critical(issues) is True

    def test_check_agent_available(self):
        """Debe verificar disponibilidad de agentes."""
        wrapper = AIAgentWrapper()

        # Claude y opencode no deberían estar disponibles en el test
        assert wrapper.check_agent_available("claude") is False
        assert wrapper.check_agent_available("opencode") is False

    def test_wrapper_result_structure(self):
        """Debe retornar estructura correcta."""
        wrapper = AIAgentWrapper()

        prompt = "test"
        config = WrapperConfig(agent_command="demo")

        result = wrapper.run(prompt, config)

        assert isinstance(result, WrapperResult)
        assert hasattr(result, "success")
        assert hasattr(result, "stdout")
        assert hasattr(result, "sanitized_input")
        assert hasattr(result, "sanitized_output")
        assert hasattr(result, "security_issues_found")
        assert hasattr(result, "blocked")


class TestWrapperConfig:
    """Tests para WrapperConfig."""

    def test_default_config(self):
        """Debe tener valores por defecto."""
        config = WrapperConfig()

        assert config.sanitize_input is True
        assert config.sanitize_output is True
        assert config.prune_context is False
        assert config.block_critical is True
        assert config.agent_command == "claude"

    def test_custom_config(self):
        """Debe aceptar configuración personalizada."""
        config = WrapperConfig(
            agent_command="opencode",
            sanitize_input=False,
            prune_context=True,
            context_file="app.py",
        )

        assert config.agent_command == "opencode"
        assert config.sanitize_input is False
        assert config.prune_context is True
        assert config.context_file == "app.py"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
