"""
🛡️ ZTC-Wrapper - Tests Unitarios

Tests para el sanitizer de metadatos.
"""

import pytest
from src.sanitizer import MetadataSanitizer, sanitize_code


class TestMetadataSanitizer:
    """Tests para el MetadataSanitizer."""

    def test_remove_absolute_paths_windows(self):
        """Debe limpiar rutas absolutas de Windows."""
        code = 'path = "C:/Users/Leoshi/Documents/project.py"'
        result = MetadataSanitizer().sanitize(code)

        assert "C:/Users" not in result.cleaned_code
        assert "./project.py" in result.cleaned_code

    def test_remove_absolute_paths_linux(self):
        """Debe limpiar rutas absolutas de Linux."""
        code = 'path = "/home/user/project/main.py"'
        result = MetadataSanitizer().sanitize(code)

        assert "/home/user" not in result.cleaned_code
        assert "./main.py" in result.cleaned_code

    def test_remove_ai_comments(self):
        """Debe eliminar comentarios de IA."""
        code = "// Generated by Claude Code\ndef foo(): pass"
        result = MetadataSanitizer().sanitize(code)

        assert "Generated by" not in result.cleaned_code

    def test_remove_thinking_comments(self):
        """Debe eliminar comentarios de pensamiento."""
        code = "// Thinking: This is a test\ndef foo(): pass"
        result = MetadataSanitizer().sanitize(code)

        assert "Thinking" not in result.cleaned_code

    def test_remove_session_tokens(self):
        """Debe eliminar tokens de sesión."""
        code = 'session_id = "abc-123-def"'
        result = MetadataSanitizer().sanitize(code)

        assert "abc-123-def" not in result.cleaned_code
        assert "[REDACTED]" in result.cleaned_code

    def test_remove_model_signatures(self):
        """Debe eliminar firmas de modelos."""
        code = 'model_id = "gpt-4-turbo"'
        result = MetadataSanitizer().sanitize(code)

        assert "gpt-4" not in result.cleaned_code

    def test_preserve_code_logic(self):
        """Debe preservar la lógica del código."""
        code = """
def calculate(x, y):
    return x + y * 2

result = calculate(10, 5)
"""
        result = MetadataSanitizer().sanitize(code)

        assert "def calculate" in result.cleaned_code
        assert "return x + y * 2" in result.cleaned_code
        assert "calculate(10, 5)" in result.cleaned_code

    def test_empty_code(self):
        """Debe manejar código vacío."""
        result = MetadataSanitizer().sanitize("")

        assert result.cleaned_code == ""
        assert len(result.removed_items) == 0

    def test_convenience_function(self):
        """Test de la función de conveniencia."""
        code = 'session_id = "token-123"'
        result = sanitize_code(code)

        assert "token-123" not in result
        assert "[REDACTED]" in result


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
