"""
🛡️ ZTC-Wrapper - Sanitizador de Metadatos (Ghost-Cleaner)

Este módulo limpia el código generado por agentes de IA:
- Rutas absolutas → relativas
- Comentarios de pensamiento interno
- IDs de sesión y tokens
- Firmas de modelos de IA
"""

import re
from typing import List, Tuple
from dataclasses import dataclass


@dataclass
class SanitizeResult:
    """Resultado de la sanitización."""

    cleaned_code: str
    removed_items: List[Tuple[str, str]]  # (tipo, contenido_reemplazado)


class MetadataSanitizer:
    """Limpiador de metadatos para código generado por IA."""

    # Patrones de rutas absolutas (Windows/Linux/Mac)
    ABSOLUTE_PATH_PATTERN = re.compile(
        r"(?:[A-Za-z]:\\|/home/|/Users/|/root/|C:/|D:/|E:/)(?:[^\s*/\\]+[/\\])*[^\s*/\\]+"
    )

    # Patrones de comentarios de IA
    AI_COMMENT_PATTERNS = [
        re.compile(r"//\s*(?:THINKING|Thought|Reasoning)[:\s].*", re.IGNORECASE),
        re.compile(r"//\s*Generated by\s+.*", re.IGNORECASE),
        re.compile(r"#\s*(?:THINKING|Thought|Reasoning)[:\s].*", re.IGNORECASE),
        re.compile(r'""".*?(?:AI|Model|Generated).*?"""', re.IGNORECASE | re.DOTALL),
        re.compile(r"'''.*?(?:AI|Model|Generated).*?'''", re.IGNORECASE | re.DOTALL),
    ]

    # Patrones de IDs de sesión y tokens
    SESSION_TOKEN_PATTERNS = [
        re.compile(
            r'session[_-]?id["\']?\s*[:=]\s*["\'][a-zA-Z0-9-]+["\']', re.IGNORECASE
        ),
        re.compile(
            r'model[_-]?id["\']?\s*[:=]\s*["\'][a-zA-Z0-9-_:.-]+["\']', re.IGNORECASE
        ),
        re.compile(
            r'trace[_-]?id["\']?\s*[:=]\s*["\'][a-zA-Z0-9-]+["\']', re.IGNORECASE
        ),
    ]

    # Firmas conocidas de modelos de IA
    MODEL_SIGNATURES = [
        re.compile(r"claude[_-]?code", re.IGNORECASE),
        re.compile(r"open[_-]?code", re.IGNORECASE),
        re.compile(r"gpt[_-]?(?:3\.5|4|4[_-]?turbo)", re.IGNORECASE),
        re.compile(r" anthropic", re.IGNORECASE),
    ]

    def sanitize(self, code: str) -> SanitizeResult:
        """
        Limpia el código de metadatos.

        Args:
            code: Código original generado por la IA

        Returns:
            SanitizeResult con el código limpio y lista de elementos removidos
        """
        removed_items = []
        cleaned = code

        # 1. Limpiar rutas absolutas
        cleaned, paths_removed = self._remove_absolute_paths(cleaned)
        removed_items.extend(paths_removed)

        # 2. Limpiar comentarios de IA
        cleaned, comments_removed = self._remove_ai_comments(cleaned)
        removed_items.extend(comments_removed)

        # 3. Limpiar tokens y session IDs
        cleaned, tokens_removed = self._remove_session_tokens(cleaned)
        removed_items.extend(tokens_removed)

        # 4. Limpiar firmas de modelos
        cleaned, signatures_removed = self._remove_model_signatures(cleaned)
        removed_items.extend(signatures_removed)

        return SanitizeResult(cleaned_code=cleaned, removed_items=removed_items)

    def _remove_absolute_paths(self, code: str) -> Tuple[str, List[Tuple[str, str]]]:
        """Reemplaza rutas absolutas por rutas relativas."""
        removed = []

        def replace_path(match):
            original = match.group(0)
            # Convertir a ruta relativa básica
            filename = original.split("/")[-1].split("\\")[-1]
            replaced = f"./{filename}"
            removed.append(("absolute_path", original))
            return replaced

        cleaned = self.ABSOLUTE_PATH_PATTERN.sub(replace_path, code)
        return cleaned, removed

    def _remove_ai_comments(self, code: str) -> Tuple[str, List[Tuple[str, str]]]:
        """Elimina comentarios generados por la IA."""
        removed = []

        for pattern in self.AI_COMMENT_PATTERNS:
            matches = pattern.findall(code)
            for match in matches:
                removed.append(("ai_comment", match))
            code = pattern.sub("", code)

        return code, removed

    def _remove_session_tokens(self, code: str) -> Tuple[str, List[Tuple[str, str]]]:
        """Elimina IDs de sesión y tokens."""
        removed = []

        for pattern in self.SESSION_TOKEN_PATTERNS:
            matches = pattern.findall(code)
            for match in matches:
                removed.append(("session_token", match))
            code = pattern.sub("[REDACTED]", code)

        return code, removed

    def _remove_model_signatures(self, code: str) -> Tuple[str, List[Tuple[str, str]]]:
        """Elimina firmas de modelos de IA."""
        removed = []

        for pattern in self.MODEL_SIGNATURES:
            matches = pattern.findall(code)
            for match in matches:
                removed.append(("model_signature", match))
            code = pattern.sub("[MODEL]", code)

        return code, removed


def sanitize_code(code: str) -> str:
    """
    Función de conveniencia para sanitizar código.

    Args:
        code: Código a sanitizar

    Returns:
        Código limpio
    """
    sanitizer = MetadataSanitizer()
    return sanitizer.sanitize(code).cleaned_code


if __name__ == "__main__":
    # Ejemplo de uso
    sample_code = """
// Generated by Claude Code
// Thinking: This function needs validation

def process_data(path: str):
    # Absolute path: C:/Users/Leoshi/Documents/project/src/main.py
    return open('/home/user/secrets/api_key.txt').read()
    
session_id = "abc-123-def-456"
model_id = "gpt-4-turbo"
    """

    sanitizer = MetadataSanitizer()
    result = sanitizer.sanitize(sample_code)

    print("=== Código Original ===")
    print(sample_code)
    print("\n=== Código Limpiado ===")
    print(result.cleaned_code)
    print("\n=== Elementos Removidos ===")
    for tipo, contenido in result.removed_items:
        print(f"  [{tipo}]: {contenido[:50]}...")
